wporter/air-quality

package-lock.json
package.json
src/app/globals.css
src/app/layout.js
src/app/page.js
src/components/Map.jsx

Map Component

---

src/app/page.js
src/components/Welcome.jsx

Landing Fixes

---

src/app/page.js
src/components/Map.jsx
src/components/researcher/Map.jsx
src/components/researcher/Status.jsx

Setup Map in Researcher Dashboard

---

src/components/researcher/dashboard/Map.jsx
src/components/researcher/dashboard/Status.jsx
tailwind.config.js

Status component styled

---

src/components/researcher/SideNavigation.jsx
src/components/researcher/dashboard/Status.jsx

Notes:
- couldn't find the exact "people" icon w/ react icons 
- the 2 "menu option" options in the nav bar temporarily route to /researcher for now

Researcher's side navigation bar done

---

public/svg/errorWaves.svg
src/app/error.js
src/app/not-found.js
src/components/BackToHomeButton.jsx
src/components/Error.jsx
src/components/ErrorNavigation.jsx

Notes:
- created another component for the "return back to home page" button...when you click on it, you return back to the home page

Error handling pages completed 

---

src/app/page.js
src/components/researcher/Tag.jsx
tailwind.config.js

added tag component and fixed styling

---

src/app/layout.js
src/app/page.js
src/components/Footer.jsx

- created footer and added to layout 
- can link email later when dummy email is no longer in use

Added footer

---

src/components/Footer.jsx
src/components/Navigation.jsx
src/components/researcher/Navigation.jsx
src/components/researcher/Protected.jsx
src/components/researcher/SideNavigation.jsx
src/components/researcher/Tag.jsx
src/components/researcher/dashboard/Data.jsx
src/components/researcher/dashboard/Map.jsx
tailwind.config.js

- some fixing still needs to be done w/ the table itself

Touch ups on researcher's view page 

---

src/components/Error.jsx
src/components/about/Profile.jsx

Fixed issues with footer on error page

---

package-lock.json
package.json
src/components/researcher/data/Data.jsx

removed the geolocation

---

src/components/Footer.jsx
tailwind.config.js

Removed contact info from footer

---

src/components/researcher/data/Data.jsx
src/components/researcher/data/Details.jsx
tailwind.config.js

styled the device detailed data

---

package-lock.json
src/components/researcher/dashboard/Data.jsx
src/components/researcher/dashboard/Dropdown.jsx
tailwind.config.js

dropdown done

---

cypress/component/Tag.cy.js
src/components/researcher/Tag.jsx

Add Tag Tests

---

cypress/component/Error.cy.js
src/app/not-found.js
src/components/Error.jsx

Error Component Tests

---

src/components/about/About.jsx

made about page

---

src/components/researcher/dashboard/Dashboard.jsx
src/components/researcher/dashboard/Data.jsx
src/components/researcher/dashboard/Status.jsx

- Removed "welcome user"
- Fixed UI for the offline/online status boxes
- Moved map & added padding + minor UI fixes

Updated Researcher Dashboard UI

---

src/components/Navigation.jsx

distance btwn about and sign-in cut down

---

src/components/researcher/dashboard/Data.jsx

- cells are the only thing that's scrollable 
- everything else stays in place

fixed scrolling for researcher's data table

---

components/researcher/data/Data.jsx
components/researcher/data/Details.jsx
components/researcher/data/Line.jsx
utils/api.js

Unique Graphs

---

components/researcher/Tag.jsx
components/researcher/dashboard/Data.jsx
data/Tags.js
tailwind.config.js

- re-added correct color for when user hovers over a row on the table 
- made tags on table more round 
- changed <Tag /> component so that it can accept an optional "Icon" prop 
- made header of table round @ the top and added a margin top and bottom to each of the rows to match the design

Styling touch-ups 

---

components/researcher/data/Details.jsx

- changed to "unavailable" grey text

Fixed "unavailable" UI

---

src/components/researcher/SideNavigation.jsx

added drop shadow and fixed spacing

cleaned up Nav bar ui

---

src/components/researcher/dashboard/Dashboard.jsx

lined the status with map

---

src/app/page.js
src/components/Welcome.jsx

Page scrolls to "Public View" section when user clicks on arrow.

Added scroll on-click

---

src/components/Error.jsx
src/components/about/About.jsx

- about page fixed up
- error pages fixed small spacing

ui clean ups

---

src/components/about/About.jsx
src/components/about/Profile.jsx

- adjusted spacing between sections
- enlarged text sizing and adjusted it to certain screen sizes
- adjusted "our team" placeholder pics spacing and columns

UI Clean up

---

package-lock.json
src/app/layout.js
src/components/AqiStatus.jsx
src/components/Error.jsx
src/components/Legend.jsx
src/components/Map/Content.jsx
src/components/Marker.jsx
src/data/StatusAqi.js
tailwind.config.js

- added legend w/ traditional aqi colors 
- map markers now are colored based on the aqi in that location + display aqi value 
- tool tip now has a circle next to the sn that's based on the aqi value 
Front-end touch ups: 
- added a hover effect to error page 
- fixed metadata due to misspelling 😭

Map features implemented

---

src/components/AqiStatus.jsx

Updated markers to have no border

---

src/components/researcher/dashboard/Dashboard.jsx
src/utils/api.js

map issue on deployment gone and sensor status issue fixed

---

src/components/about/About.jsx

fixed issue with footer

---

src/components/researcher/dashboard/Data.jsx

implemented sorting in data table

---

src/components/Form.jsx
src/components/Map/ArcGIS.jsx
src/components/about/About.jsx
src/components/researcher/dashboard/Dashboard.jsx
src/components/researcher/dashboard/Data.jsx
src/data/Aqi.js
src/data/StatusAqiColor.js
src/utils/api.js

- to be changed later if more information needs to be added 
- AQI value in table has the background color according to it's aqi

ArcGIS tool tips implemented 

---

src/app/hooks/Auth.js
src/components/Form.jsx

the site stays logged in even if refreshed

 fixed auth issue

---

src/components/researcher/SideNavigation.jsx

nav bar is collapsable now
